# Generated by Django 4.0.5 on 2022-06-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rel_note_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.ManyToManyField(to='home.tag'),
        ),
    ]
