# Generated by Django 4.0.5 on 2022-06-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_tag_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.RemoveField(
            model_name='note',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
        migrations.DeleteModel(
            name='rel',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
